# Generated by Django 5.0.6 on 2024-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='客户姓名')),
                ('number', models.IntegerField(max_length=15, verbose_name='客户电话')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='客户余额')),
            ],
        ),
        migrations.AlterField(
            model_name='supermanager',
            name='name',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
    ]
