# Generated by Django 5.0.6 on 2025-03-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_consumer_alter_supermanager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='客户余额'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='number',
            field=models.IntegerField(verbose_name='客户电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='月薪'),
        ),
    ]
